### ISSUE TITLE
Where's Sham-Wow's repo?

### ISSUE THREAD

**Issue by aidan-fitz** [mks66/picmaker#1]
@CodeSammich your repo's not linked properly

**Comment by CodeSammich** [comment]
I’m trying to fix it, but I’m getting a “path is ignored by .gitignore
file” error. Can’t seem to fix...

On Tue, Feb 9, 2016 at 11:10 AM, Aidan Fitzgerald <notifications@github.com>
wrote:

> @CodeSammich <https://github.com/CodeSammich> your repo's not linked
> properly
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mks66/picmaker/issues/1>.
>



-- 
Samuel Zhang
samuelzhang3@gmail.com
